### ISSUE TITLE
Issues with BadgeOS

### ISSUE THREAD

**Issue by excellins** [opencredit/badgeos#542] opened 2016-07-07 19:27 UTC
Achievement link doesn't show up on WordPress user profile even though i installed the community addon. during first installation it was there, later on it wasnt seen anymore... now there is no link to view achievements

**Comment by asahi-badgeos** [comment] 2016-07-20 04:10
I'm closing this issue since it's a duplicate of #540 .  We can correspond there.

**Closed by asahi-badgeos** 2016-07-20 04:10 UTC
