### ISSUE TITLE
URL for submission / nomination (was "URL for achivement")

### ISSUE THREAD

**Issue by cyclingzealot** [opencredit/badgeos#466] opened 2015-07-20 21:31 UTC
Hello,

 I'm just wondering if there's a URL for an achievement, that is, the join of one user and one badge.  We were hoping to improve the presentation of one achievement for a user, among other things, showing or linking to the proof. 

The following URLs exist:

* **For a user's earned badges**: ```http://$host/members/$username/achievements/``` has the list of badges this user has earned
* **For a badge**:  Click on one badge , that brings me to ```http://$host/badges/$badgeName/``` , which list the earners of the badge.  I would hope it could link me to an achievement, not a badge. 
* **For an activity**: ```http://$host/members/$username/activity/$activityID/``` does show us the badge earning.  Though not ideal, it could provide what we need if I can find a template for an activity and can find a way to query for activity related to a specified user and badge.

Some of the above links may be provided by buddy press.

 Perhaps I don't have the good theme for badgeos? We are using the engage theme (http://themeforest.net/item/engage-wordpress-buddypress-bbpress-theme/4288994).

**Comment by tw2113** [comment] 2015-07-20 22:09
First bullet point is one we set up in the Community Addon, and it uses the [badgeos_achievements_list] shortcode if I recall right, or at least the same functions as the shortcode.

Second bullet point is linking to a single badge in the badge achievement type. Since achievement types are done as post types with BadgeOS, they get archives, and thus also single urls for the post/achievement. This should definitely be customizable, just need to create/edit the correct template file. I believe we use the_content to filter in the earners. The template would be `archive-$achievement_type.php` and `single-$achievement_type.php` with `$achievement_type` being replaced by the slug.

Third bullet point is a bit more difficult, because we're not necessarily provided with much to go off of. The template used for this is located at `/buddypress/bp-templates/bp-legacy/buddypress/activity/entry.php` and should be overrideable in your theme in similar ways to how WooCommerce and The Events Calendar do it. Just need to put the files in the right folder in your active theme. The issue is getting the user/badge information so you have more to query with for that part. Without diving too far in, we'd have the activity ID, but I am not sure if you can get user IDs with that,

**Comment by cyclingzealot** [comment] 2015-07-20 23:38
­­
> The template would be archive-$achievement_type.php and single-$achievement_type.php with $achievement_type being replaced by the slug.

So somewhere in ```wordpress/wp-content/themes/engage``` I should have a file called, using badge stack achivement types as an example:
* For quests
  * ```archive-quest.php``` 
  * ```single-quest.php```
* For quest badges:
  * ```archive-quest-badge.php``` 
  * ```single-quest-badge.php```
* For levels:
  * ```archive-level.php``` 
  * ```single-level.php```

... if I wanted to make a template for all those 3 achievement types?


I'm not sure how to get Wordpress to use those templates, but its something I will RTFM for.

**Comment by tw2113** [comment] 2015-07-20 23:59
Yep, I do believe so. It'll happen automatically too. I recommend making a duplicate of archive.php and single.php and edit as necessary for each achievement type you want to customize the display for. If it gets too tedious, there would be ways around it without so much file duplication, but you'd need to get into post type checking and conditional loading of separate files. I can type up an example if we get to that point.

**Comment by cyclingzealot** [comment] 2015-07-21 05:55
I think I got mixed up in my badgeos lingo.  I think what badgeos calls approved submissions and approved nominations I was calling achievements (to refer to the join between a user and a badgeos achievement)

When I see the list of achievements a user has earned (at http://$host/members/$username/achievements/) and click on one, I would like it to go to the submission or nomination to see the details rather then the generic achievement.

I note there is a shortcode (badgeos_nominations.php  badgeos_submissions.php) to list nominations and submissions.  I see that the badgeos_submissions shortcode does have a filter to view only approved submissions.  But I'd want approved submissions to be public (viewable to all) whereas currently "If the current user does not have the ability to review Submissions, they will instead see just their own Submissions."

I see that there is an existing ticket for this enhancement: https://github.com/opencredit/badgeos/issues/392 .  I'm going to comment in that ticket then test the shortcode, see if the documentation is accurate.  

If we agree in #392 how we want to proceed then I will close this ticket.

**Comment by cyclingzealot** [comment] 2015-07-21 06:06
*Update*: Unfortunately I'm not entirely sure using the shortcode would answer our needs, as I think we want to link to a submission from the list of achievements (http://$host/members/$username/achievements/).  

I'll still comment in #392 and reflect on how to proceed.

**Comment by cyclingzealot** [comment] 2015-07-21 06:31
Ok, I think what I'd want to do is modify line 408 of ```wp-content/plugins/badgeos/includes/content-filters.php```:

```php
408     $output .= '<div id="badgeos-achievements-list-item-' . $achievement->ID . '" class="badgeos-achievements-list-item '. $earned_status . $credly_class .'"'. $cre    dly_ID .'>';
409 
410         // Achievement Image
411         $output .= '<div class="badgeos-item-image">';
412         $output .= '<a href="' . get_permalink( $achievement->ID ) . '">' . badgeos_get_achievement_post_thumbnail( $achievement->ID ) . '</a>';
```

to get the ID of the submission rather then the achievement.  But I'm not sure that's what you'd want.  

Perhaps, somewhere in the excerpt generated in the code below, I could add a "See submission details..." 

```php
421             // Achievement Short Description
422             $output .= '<div class="badgeos-item-excerpt">';
423             $output .= badgeos_achievement_points_markup( $achievement->ID );
424             $excerpt = !empty( $achievement->post_excerpt ) ? $achievement->post_excerpt : $achievement->post_content;
425             $output .= wpautop( apply_filters( 'get_the_excerpt', $excerpt ) );
426             $output .= '</div><!-- .badgeos-item-excerpt -->';
```

**Comment by tw2113** [comment] 2015-07-21 06:40
You can output whatever you want with that filter. My recommendation is to only alter for the conditions you know you want to, and return the unaltered version for everything else.

Admittedly not always easy to fetch every part you may need though, which makes our customization bits more complex than they should be at times, and those would be for other PRs and whatnot to make it easier.

**Comment by cyclingzealot** [comment] 2015-07-21 20:54
I see the call to global $user_ID.  Is this the ID of the authenticated user or the user ID of the profile we are looking at?

 ```php
382 function badgeos_render_achievement( $achievement = 0 ) {
383     global $user_ID;
384 
385     // If we were given an ID, get the post
386     if ( is_numeric( $achievement ) )
387         $achievement = get_post( $achievement );
388 
389     // make sure our JS and CSS is enqueued
390     wp_enqueue_script( 'badgeos-achievements' );
391     wp_enqueue_style( 'badgeos-widget' );
392 
393     // check if user has earned this Achievement, and add an 'earned' class
394     $earned_status = badgeos_get_user_achievements( array( 'user_id' => $user_ID, 'achievement_id' => absint( $achievement->ID ) ) ) ? 'user-has-earned' : 'user-has-not-earned';
```

**Comment by cyclingzealot** [comment] 2015-07-21 21:29
Never mind.  I outputted in the title and its the authenticated user.   I need the ID of user for which I pulled up a profile for.

**Comment by tw2113** [comment] 2015-07-21 21:48
For BuddyPress: `bp_displayed_user_id()`

**Closed** 2015-09-19 22:52 UTC
